import pygame
pygame.init()

DISPLAY_SIZE = pygame.display.get_desktop_sizes()[0]
SCREEN_WIDTH, SCREEN_HEIGHT = (DISPLAY_SIZE[0] - 178), (DISPLAY_SIZE[1] - 100)



GAME_SPEED = 60
ASTEROID_SPAWN_RATE = 2.5  # seconds orginal was 0.8

PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_BULLET_TTL = 35

SHOT_RADIUS = 2
SHOT_VELOCITY = 10